// rolodex-data.jsx — platform metadata: colors, fonts, deep links
// Fonts chosen to subtly evoke each app's typographic feel (system-safe fallbacks)

const PLATFORMS = {
  instagram: {
    name: 'Instagram',
    bg: 'linear-gradient(135deg, #515BD4 0%, #8134AF 25%, #DD2A7B 50%, #FEDA77 90%, #F58529 100%)',
    solid: '#E1306C',
    qrColor: '#C13584',
    text: '#fff',
    handleFont: '"Instagram Sans", "Rubik", "Helvetica Neue", sans-serif',
    handleWeight: 700,
    placeholder: 'rob.wan',
    format: (h) => `instagram.com/${h.replace(/^@/, '')}`,
    deepLink: (h) => `https://instagram.com/${h.replace(/^@/, '')}`,
    prefix: '@',
  },
  tiktok: {
    name: 'TikTok',
    bg: 'linear-gradient(165deg, #010101 0%, #161616 100%)',
    solid: '#000000',
    qrColor: '#FE2C55',
    text: '#fff',
    handleFont: '"TikTok Sans", "Montserrat", "Proxima Nova", "Helvetica Neue", sans-serif',
    handleWeight: 700,
    placeholder: 'rob.wan',
    format: (h) => `tiktok.com/@${h.replace(/^@/, '')}`,
    deepLink: (h) => `https://tiktok.com/@${h.replace(/^@/, '')}`,
    prefix: '@',
  },
  twitter: {
    name: 'X',
    bg: '#000000',
    solid: '#000000',
    qrColor: '#000000',
    text: '#fff',
    handleFont: '"Chirp", "Inter", "Helvetica Neue", sans-serif',
    handleWeight: 700,
    placeholder: 'robbthefobb',
    format: (h) => `x.com/${h.replace(/^@/, '')}`,
    deepLink: (h) => `https://x.com/${h.replace(/^@/, '')}`,
    prefix: '@',
  },
  linkedin: {
    name: 'LinkedIn',
    bg: 'linear-gradient(165deg, #0A66C2 0%, #004182 100%)',
    solid: '#0A66C2',
    qrColor: '#0A66C2',
    text: '#fff',
    handleFont: '"Source Sans 3", "Helvetica Neue", sans-serif',
    handleWeight: 600,
    placeholder: 'robwan-ai',
    format: (h) => `linkedin.com/in/${h}`,
    deepLink: (h) => `https://linkedin.com/in/${h}`,
    prefix: 'in/',
  },
  whatsapp: {
    name: 'WhatsApp',
    bg: 'linear-gradient(165deg, #25D366 0%, #128C7E 100%)',
    solid: '#25D366',
    qrColor: '#128C7E',
    text: '#fff',
    handleFont: '"Helvetica Neue", sans-serif',
    handleWeight: 500,
    placeholder: '1-647-778-3778',
    format: (h) => `wa.me/${h.replace(/[^\d]/g, '')}`,
    deepLink: (h) => `https://wa.me/${h.replace(/[^\d]/g, '')}`,
    prefix: '',
  },
  facebook: {
    name: 'Facebook',
    bg: 'linear-gradient(165deg, #1877F2 0%, #0a4db0 100%)',
    solid: '#1877F2',
    qrColor: '#1877F2',
    text: '#fff',
    handleFont: '"Facebook Sans", "Inter", "Helvetica Neue", sans-serif',
    handleWeight: 700,
    placeholder: 'rob.wan',
    format: (h) => `facebook.com/${h}`,
    deepLink: (h) => `https://facebook.com/${h}`,
    prefix: '',
  },
  snapchat: {
    name: 'Snapchat',
    bg: '#FFFC00',
    solid: '#FFFC00',
    qrColor: '#000000',
    text: '#000',
    handleFont: '"Avenir Next", "Helvetica Neue", sans-serif',
    handleWeight: 700,
    placeholder: 'rob.wan',
    format: (h) => `snapchat.com/add/${h}`,
    deepLink: (h) => `https://snapchat.com/add/${h}`,
    prefix: '',
  },
  discord: {
    name: 'Discord',
    bg: 'linear-gradient(165deg, #5865F2 0%, #404ab8 100%)',
    solid: '#5865F2',
    qrColor: '#5865F2',
    text: '#fff',
    handleFont: '"gg sans", "Noto Sans", "Whitney", "Helvetica Neue", sans-serif',
    handleWeight: 600,
    placeholder: 'robwan',
    format: (h) => `discord.com/users/${h}`,
    deepLink: (h) => `https://discord.com/users/${h}`,
    prefix: '',
  },
  telegram: {
    name: 'Telegram',
    bg: 'linear-gradient(165deg, #2AABEE 0%, #229ED9 100%)',
    solid: '#229ED9',
    qrColor: '#229ED9',
    text: '#fff',
    handleFont: '"Roboto", "Helvetica Neue", sans-serif',
    handleWeight: 500,
    placeholder: 'robwan',
    format: (h) => `t.me/${h.replace(/^@/, '')}`,
    deepLink: (h) => `https://t.me/${h.replace(/^@/, '')}`,
    prefix: '@',
  },
  venmo: {
    name: 'Venmo',
    bg: 'linear-gradient(165deg, #3D95CE 0%, #1e5e8a 100%)',
    solid: '#3D95CE',
    qrColor: '#008CFF',
    text: '#fff',
    handleFont: '"Graphik", "Figtree", "Helvetica Neue", sans-serif',
    handleWeight: 600,
    placeholder: 'Robert-Wan',
    format: (h) => `venmo.com/${h}`,
    deepLink: (h) => `https://venmo.com/${h}`,
    prefix: '@',
  },
  cashapp: {
    name: 'Cash App',
    bg: '#00D632',
    solid: '#00D632',
    qrColor: '#00D632',
    text: '#000',
    handleFont: '"Cash Sans", "Manrope", "Helvetica Neue", sans-serif',
    handleWeight: 700,
    placeholder: 'robwan',
    format: (h) => `cash.app/$${h}`,
    deepLink: (h) => `https://cash.app/$${h}`,
    prefix: '$',
  },
  website: {
    name: 'Website',
    bg: 'linear-gradient(165deg, #1a1a1a 0%, #3a3a3a 100%)',
    solid: '#1a1a1a',
    qrColor: '#1a1a1a',
    text: '#fff',
    handleFont: '"Instrument Serif", serif',
    handleWeight: 400,
    placeholder: 'robwan.co',
    format: (h) => h,
    deepLink: (h) => `https://${h}`,
    prefix: '',
  },
};

const DEFAULT_CARDS = [
  { id: 'c1', platform: 'instagram', handle: 'rob.wan', scans: 47, favorite: true },
  { id: 'c2', platform: 'linkedin', handle: 'robwan-ai', scans: 124, favorite: true },
  { id: 'c3', platform: 'twitter', handle: 'robbthefobb', scans: 18, favorite: false },
  { id: 'c4', platform: 'whatsapp', handle: '1-647-778-3778', scans: 31, favorite: true },
  { id: 'c5', platform: 'telegram', handle: 'robwan', scans: 9, favorite: false },
  { id: 'c6', platform: 'tiktok', handle: 'rob.wan', scans: 6, favorite: false },
  { id: 'c7', platform: 'venmo', handle: 'Robert-Wan', scans: 12, favorite: false },
  { id: 'c8', platform: 'website', handle: 'robwan.co', scans: 22, favorite: false },
];

Object.assign(window, { PLATFORMS, DEFAULT_CARDS });
